[package]
name = "lingo"
version = "0.3.0"
authors = ["Martin Sandgren <carlmartus@gmail.com>"]

[dependencies]
glutin = "0.13"
gl = "0.10"

[[example]]
name = "hello_triangle"
path = "samples/hello_triangle.rs"

[[example]]
name = "camera"
path = "samples/camera.rs"

[[example]]
name = "stride"
path = "samples/stride.rs"
