[package]
name = "lingo"
version = "0.0.0"
authors = ["Martin Sandgren <carlmartus@gmail.com>"]
build = "build.rs"

[build-dependencies]
git-build-version = "0.1.2"

[dependencies]
glutin = "0.13"
gl = "0.10"

[[bin]]
name = "sample"
path = "src/sample.rs"
