[package]
name = "lingo"
version = "0.2.0"
authors = ["Martin Sandgren <carlmartus@gmail.com>"]

[dependencies]
glutin = "0.13"
gl = "0.10"

[[bin]]
name = "hello_triangle"
path = "samples/hello_triangle.rs"

[[bin]]
name = "camera"
path = "samples/camera.rs"
